// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN1vHO34SCIYjxSdouQuyTWf6kFnzLpGI',
    appId: '1:791807935214:web:f72379c225eaab4375a9ff',
    messagingSenderId: '791807935214',
    projectId: 'projekambw',
    authDomain: 'projekambw.firebaseapp.com',
    storageBucket: 'projekambw.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3m6MFqHB-2H1CS1iXr1QXwIpuDWf6l1Y',
    appId: '1:791807935214:android:f90da8447d751cc075a9ff',
    messagingSenderId: '791807935214',
    projectId: 'projekambw',
    storageBucket: 'projekambw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdu5_7sA4Q6SIzmbuJxTumTLUWXhg4iCI',
    appId: '1:791807935214:ios:e078c8a73b2cae5075a9ff',
    messagingSenderId: '791807935214',
    projectId: 'projekambw',
    storageBucket: 'projekambw.appspot.com',
    iosClientId: '791807935214-3k3k2md1rcjg2qru43cgoa79t1g9bkrj.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectAmbw',
  );
}
