// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP8XTBEAL8rLwYCXsTK1jotLaFfvBNPOc',
    appId: '1:148065823875:web:3bb51f1685c8fd76d87fb6',
    messagingSenderId: '148065823875',
    projectId: 'test2ambw',
    authDomain: 'test2ambw.firebaseapp.com',
    storageBucket: 'test2ambw.appspot.com',
    measurementId: 'G-JGVCBBV6JH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALsFZMY4qNn0LF445ziygX8QrU_HtDlwo',
    appId: '1:148065823875:android:04ec19a5f4e4d968d87fb6',
    messagingSenderId: '148065823875',
    projectId: 'test2ambw',
    storageBucket: 'test2ambw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADMom-I7uKg4IxJwJzM4KX1DWBplzlfIA',
    appId: '1:148065823875:ios:5570a3e9420634d4d87fb6',
    messagingSenderId: '148065823875',
    projectId: 'test2ambw',
    storageBucket: 'test2ambw.appspot.com',
    iosClientId: '148065823875-ac3v0fmr83cnc9ule1d647cqokuflg50.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikasiBookingLapanganOnline',
  );
}
